### ISSUE TITLE
Module Not Found Error for scipy.interpolate._fitpack2

### ISSUE THREAD

**Issue by maheen-tariq** [mceq-project/daemonflux#1]
Error when calling Flux(location='generic') for Scipy 1.7.3. Please find attached image for traceback. 
<img width="1061" alt="Screen Shot 2023-03-01 at 3 32 47 PM" src="https://user-images.githubusercontent.com/123414759/222329009-a5349d7e-1744-451d-b4a2-da1238fbff4f.png">

**Comment by marialiubarska** [comment]
@afedynitch @jpyanez I also experienced the same issue with python 3.7 and scipy 1.7.3 (which is the maximum version available for python 3.7). 

It looks like `scipy.interpolate._fitpack2` was added in 1.8.1 release, which requires at least python 3.8, but the requirement for daemonflux is `python >=3.7` and there is no version requirement on scipy. At the same time `scipy.interpolate.fitpack2` is available in earlier releases of scipy.

**Comment by afedynitch** [comment]
@marialiubarska Thanks for providing more details. I’m gonna bump the minimal requirements on python to 3.8 since 3.7 is deprecated. Nonetheless, I’ll try bringing back the hack @jpyanez used to cure this problem, just to make it a bit more compatible with older versions.
