### ISSUE TITLE
Flat distributions for up-going neutrinos for generic and Kamioka sites.

### ISSUE THREAD

**Issue by NadjaLessing** [mceq-project/daemonflux#8]
For directions with cos(theta_zenith) < 0 (up-going) the neutrino flux distribution are flat for the 'generic' and 'Kamioka' sites.
![image](https://github.com/mceq-project/daemonflux/assets/85738841/356f01fe-e019-4e15-b05f-ac00f4b813e6)

**Comment by afedynitch** [comment]
Hi @NadjaLessing & @pochoarus!

Thanks for reporting this.

Could you let me know how you got this figure?
With the latest public version, I get the following:
```
plt.figure()
zendist = []
czeniths = np.linspace(-1, 1, 30)
for czen in czeniths:
    zendist.append(fl.flux([1e3], np.degrees(np.arccos(czen)), "numuflux").squeeze())
plt.semilogy(
    czeniths, zendist, color="c", label="conv: calibrated")
plt.xlabel("cos(zenith)")
plt.ylabel("E*3 Flux")
plt.legend()
plt.tight_layout()

>>> ValueError: Requested zenith angles must be within the range 0.0000 - 90.0000
```

**Comment by NadjaLessing** [comment]
Never mind, I just found an error in my script.
You are right, the daemonflux output only gives values between 0 and 90 degrees for generic. 
Apologies.

**Comment by afedynitch** [comment]
Good to know! Thanks for reporting back.

Closing.
